export const SAVE_USER_DETAILS = 'SAVE_USER_DETAILS';
export const SAVE_DEVELOPERS = 'SAVE_DEVELOPERS';
export const SAVE_CURRENT_DEV = 'SAVE_CURRENT_DEV';
export const SAVE_APPOINTMENTS = 'SAVE_APPOINTMENTS';
