export const SAVE_CURRENT_USER = 'SAVE_CURRENT_USER';
export const SAVE_DEVELOPERS = 'SAVE_DEVELOPERS';
export const SAVE_CURRENT_DEV = 'SAVE_CURRENT_DEV';
export const SAVE_APPOINTMENTS = 'SAVE_APPOINTMENTS';
